pocket-id/website

.github/ISSUE_TEMPLATE/docs.yml
Add issue template for documentation requests, in the event someone ones opens issues vs just a PR for doc additions
=> add docs.yml issue template

docs/client-examples/forgejo.md, docs/client-examples/grafana.md, sidebars.ts
Added client examples for forgejo and grafana. For forgejo, I have reused the gitea page content and updated where required.
=> docs: client example for forgejo and grafana

docs/client-examples/audiobookshelf.md
Added a client Example for Audiobookshelf. Grammar and spelling mistake check and nit-picking welcome 😁!
=> docs: add Client Example for Audiobookshelf

.github/workflows/deploy-docs.yml, .github/workflows/test-deployment.yml, docs/client-examples/freshrss.md, docusaurus.config.ts
Fixes: https://github.com/pocket-id/website/issues/29
=> docs: cleanup and update to openapi3 docs

docs/client-examples/bookstack.md
=> New client bookkstack - https://www.bookstackapp.com/

docs/configuration/environment-variables.md
Relates-to: pocket-id/pocket-id#495
=> feat: Add observability documentation

docs/configuration/environment-variables.md
Updates to match pocket-id/pocket-id#495.
=> Observability documentation updates

docs/client-examples/mealie.md
First time contributor, I think I did this right. Let me know if you need anything more. 
Tested this with the current version of Mealie
=> Added Mealie client-example

docs/client-examples/nextcloud.md
=> docs: improve User ID mapping section for Nextcloud

docs/client-examples/wekan.md
=> docs: add Wekan client-example

docs/client-examples/actual.md
=> docs: add Actual Budget client-example

docs/client-examples/mealie.md
Callback URL is /login and not /oauth/oidc/callback
=> Update Mealie client example - callback URL

docs/client-examples/pingvin.md
Took some playing around with the role/group mapping, but I have created a working [Pingvin](https://stonith404.github.io/pingvin-share/setup/oauth2login#openid-connect) example now!
=> docs: add Pingvin client-example

docs/client-examples/bookstack.md
Updated BookStack with more info about group sync from their documents and tested.
=> docs: updates BookStack example and adds more group info

docs/client-examples/outline.md
=> docs: adds Outline client example

docs/client-examples/freshrss.md
=> docs: fix freshrss typo

docs/client-examples/donetick.md
Create the documentation to install pockerID auth on [donetick](https://donetick.com/).
It is my first contribution to the doc, and my English is not as good as I want it to be.
Feel free to guide or correct me if you think it can be improved.
Thank you again for the amazing tool you've built ;)
=> Create donetick client example

docs/setup/user-management.md
=> docs: adds basic SUT info

docs/configuration/environment-variables.md, docs/setup/advanced-topics.md
Update the docs for pocket-id/pocket-id#682 and id/pocket-id#709
=> Docs for encrypted keys

docs/client-examples/filebrowser-quantum.md
Fixes the token to be proper from [here](https://github.com/gtsteffaniak/filebrowser/issues/631#issuecomment-2906965444)
=> docs: fix username on filebrowser

docs/client-examples/cloudflare-zero-trust.md
the docs are missing one step. this fixes that.
=> fix: inconsistency in Zero Trust documentation

docs/client-examples/pinepods.md
Configuration steps based off of Pinepods' [documentation](https://www.pinepods.online/docs/tutorial-extras/OIDC-setup).
=> docs: add pinepods client example

docs/client-examples/netbox.md
A litte fix of the description for the netbox example
=> fix restart command of netbox

docs/client-examples/wallos.md
plus a bit of capitalization consistency
=> fix: wrong service mentioned in Wallos documentation
