pocket-id/website

- docs/client-examples/paperless-ngx.md
- sidebars.ts
Added a new client example page for paperless-ngx's docker based installation.
> docs: added client exmample for paperless-ngx

- src/components/feature-box.tsx
- src/pages/index.tsx
This pull request addresses two issues:
Feature Box Mobile Layout:
- Ensured that in the mobile view, the feature text (title and description) always appears above the image, regardless of the imgLeft prop, as having the title sometimes above and sometimes below the image on mobile devices felt inconsistent and unnecessary.
Footer Copyright:
- Updated the displayed copyright year to the current year.
> fix: always display feature text above image on mobile & update copyright year

- docs/client-examples/paperless-ngx.md
The current example config for paperless-ngx fails with the error below, because in the given example, the schema is missing:
```
requests.exceptions.MissingSchema: Invalid URL 'pocketid.example/.well-known/openid-configuration': No scheme supplied. Perhaps you meant https://pocketid.example.com/.well-known/openid-configuration?
```
> Update paperless-ngx client example to include schema in server_url

- docs/client-examples/linkding.md
This commit adds a guide on how to setup Pocket ID with Linkding (for deployments using docker-compose)
> docs: Add client guide for Linkding

- docs/guides/proxy-services.md
OAuth2 is really just a reverse proxy so configuring it for PocketId is really no different that configuring any other reverse proxy so I flattened the documentation out a bit.
Did some general cleanup of the instructions and added instructions for Traefik (well, pointed to the existing instructions).
> Update Proxy Services documentation

- docs/client-examples/oCIS.md
https://owncloud.dev/ocis/
While Access-Control-Allow-Origin has Pocket ID domain (https://github.com/pocket-id/pocket-id/issues/329) it is only possible with setting the Access-Control-Allow-Origin in the reverse proxy to fix the CORS error.
> oCIS Client example (ownCloud Infinite Scale)

- docs/client-examples/pangolin.md
[Pangolin recently added OIDC in 1.3.0](https://github.com/fosrl/pangolin/releases/tag/1.3.0)
I've configured it for myself and wrote a small client example section. I couldn't figure out an easy way to view the `sub` field in the Pocket ID user UI - so I've marked that as [advanced] in this example.
> Added pangolin client example

- docs/setup/installation.md
Added reference to [pocket-id chart](https://artifacthub.io/packages/helm/anza-labs/pocket-id) maintained by [anza-labs](https://github.com/anza-labs).
> feat: add docs to anza-labs chart

- docs/client-examples/freescout.md
This PR adds [FreeScout](https://freescout.net/) help desk to the examples documentation, as implemented and tested May 2025.
(I ❤️ Pocket ID!)
> docs: add FreeScout client-example

- docs/guides/proxy-services.md
This PR adds the recommended `cookie_name` variable from oauth2-proxy docs, to the config doc for that page.
From oauth2-proxy [docs](https://oauth2-proxy.github.io/oauth2-proxy/configuration/overview#cookie-options):
> The name of the cookie that the oauth_proxy creates. Should be changed to use a [cookie prefix](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#cookie_prefixes) (`__Host-` or `__Secure-`) if `--cookie-secure` is set.
This is somewhat of an opinionated change, but since `cookie_secure` was present in the Pocket ID recommended configuration before, the sample config should also probably include the recommended corresponding change to the name/prefix, to increase security and mitigate session fixation attacks.
This seems to work for me in testing, and everything I …
> docs: adds cookie_name to sample oauth2-proxy config

- docs/setup/migrate-v1.md
`pocketid/pocket-id:latest` doesn't exist (atleast publicly) on Docker Hub, so I've updated the migration guide's docker-compose.yml example to use the GitHub Container Repository
> docs: update Docker image reference in migration guide

- docs/client-examples/synology.md
I forked the `Portainer` instructions page and used it as a template for recording how to set up a `Synology` to authenticate with Pocket ID based on what worked in my experimentation.
Not sure if there's a TOC/Index that needs updating here as well, please let me know.
> Add Synology DSM instructions

- docs/client-examples/pangolin.md
Add in guidance around callback URL for Pocket ID initial setup; this scenario specifically addresses configuration with Pangolin but may also apply to other applications that require a ID/Secret/Auth&Token URLs to be provided before a callback URL is generated.
> docs: Update pangolin.md to clarify callback URL setup

- docs/configuration/analytics.md
The [release notes](https://github.com/pocket-id/pocket-id/releases/tag/v1.1.0) also mistakenly called this `DISABLE_ANALYTICS`
> Fix analytics env variable name

- docs/client-examples/actual.md
The path in the example is wrong. It does not work, as I just tried. It works without the "/path".
> fix: wrong callback url in actual guide

- docs/client-examples/healthchecks.md
Took a bit of fiddling with headers, but working example for HCIO here, using oauth2-proxy
> docs: add Healthchecks.io example

- docs/setup/advanced-topics.md
Includes instructions for running the container as non-root and with read-only root FS
See pocket-id/pocket-id#680
> docs: container security hardening

- docs/client-examples/actual.md
The links have been moved (see: https://github.com/actualbudget/docs/pull/712)
> docs: update links for Actual Budget

- docs/advanced/hardening.md
The description references using distroless images, but the image used is the regular one
> fix: incorrect image in sample

- docs/client-examples/airtrail.md
Configuration steps based off of AirTrail's [documentation](https://airtrail.johan.ohly.dk/docs/features/oauth).
> docs: add AirTrail client example
